# Docs:
# https://developers.cloudflare.com/workers/wrangler/configuration/

"$schema" = "./node_modules/wrangler/config-schema.json"
name = "glca-website"
compatibility_date = "2026-04-30"
compatibility_flags = [ "nodejs_compat" ]

main = "index.js"

[assets]
directory = "./public"
binding = "ASSETS"
not_found_handling = "404-page"

[observability]
enabled = true
